-- global constants

-- window
WINDOW_WIDTH = 400;
WINDOW_HEIGHT = 700;

-- player
PLAYER_X0 = 190;
PLAYER_Y0 = 600;
PLAYER_WIDTH = 20;
PLAYER_HEIGHT = 20;
PLAYER_HEALTH = 10;
-- red
RED_HEALTH = 15;

-- enemies
-- minion
MINION_WIDTH = 40;
MINION_HEIGHT = 40;
MINION_HEALTH = 2;
MINION_CD = 3;
MINION_DMG_MOD = 1;
-- tank
TANK_WIDTH = 80;
TANK_HEIGHT = 50;
TANK_HEALTH = 8;
TANK_CD = 5;
TANK_DMG_MOD = 2;
-- knight
KNIGHT_WIDTH = 40;
KNIGHT_HEIGHT = 40;
KNIGHT_SPEED = 350;
KNIGHT_HEALTH = 4;
KNIGHT_CD = 2;
KNIGHT_DMG_MOD = 1;
-- queen
QUEEN_X0 = 141;
QUEEN_Y0 = 1;
QUEEN_WIDTH = 120;
QUEEN_HEIGHT = 98;
QUEEN_SPEED = 250;
QUEEN_HEALTH = 20;
QUEEN_CD = 5;
QUEEN_DMG_MOD = 3;