#define _boolean 1
#define _break 2
#define _class 3
#define _double 4
#define _else 5
#define _extends 6
#define _for 7
#define _if 8
#define _implements 9
#define _int 10
#define _interface 11
#define _newarray 12
#define _println 13
#define _readln 14
#define _return 15
#define _string 16
#define _void 17
#define _while 18
#define _add 19
#define _sub 20
#define _mult 21
#define _div 22
#define _mod 23
#define _lessequal 24
#define _greaterequal 25
#define _notequal 26
#define _less 27
#define _greater 28
#define _equal 29
#define _and 30
#define _or 31
#define _not 32
#define _assignop 33
#define _semicolon 34
#define _comma 35
#define _period 36
#define _leftparen 37
#define _rightparen 38
#define _leftbracket 39
#define _rightbracket 40
#define _leftbrace 41
#define _rightbrace 42
#define _intconstant 43
#define _doubleconstant 44
#define _stringconstant 45
#define _booleanconstant 46
#define _id 47

#define _newLine 48